"""Package trigger-stub skills for installation on tools-only hosts.

ADR 0006 decision 4b: claude.ai never lets the model read MCP resources, and
an installed skill's *body* goes stale the moment the repo copy changes. So
the installable artifact stops carrying methodology at all — each generated
stub keeps the canonical skill's frontmatter verbatim (name, description,
version; the description is the auto-trigger surface and the only slow-moving
part) and replaces the body with an instruction to fetch the canonical text
via the Game Library connector's ``get_skill`` tool. Re-package and re-upload
only when frontmatter changes; methodology edits in ``skills/`` are live on
the next conversation with no reinstall.

Writes one stub folder and one zip per skill (the zip is the claude.ai
Skills upload format; the folder is for ``~/.claude/skills`` installs):

Usage:
    python scripts/package_skills.py [-o dist/skill-stubs]
"""

import argparse
import json
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from gamelib_mcp.skill_resources import _parse_frontmatter, _scan_skills

STUB_BODY_TEMPLATE = """\
# {name} (trigger stub)

This stub is generated by scripts/package_skills.py from the canonical skill
in the gamelib-mcp repository — do not edit it by hand, and do not follow an
older memory of this skill's methodology.

1. Call `get_skill(skill="{name}")` on the Game Library connector.
2. Follow the returned methodology for the current conversation. It is the
   canonical, current version; if its frontmatter version differs from this
   stub's ({version}), the fetched text wins.
3. If the Game Library connector is not available in this conversation, say
   so and ask for it to be enabled instead of improvising the methodology.
"""


def build_stub(name: str, description: str, version: str) -> str:
    # Scalars are JSON-encoded: a JSON string is a valid YAML double-quoted
    # scalar, and the descriptions contain ": " (e.g. 'Triggers: "..."'),
    # which a strict YAML parser rejects as a bare value — the canonical
    # SKILL.md files get away with it only because skill hosts parse
    # frontmatter leniently, and an upload target may not.
    frontmatter = (
        f"---\nname: {json.dumps(name)}\ndescription: {json.dumps(description)}\n"
        f"version: {json.dumps(version)}\n---\n\n"
    )
    return frontmatter + STUB_BODY_TEMPLATE.format(name=name, version=version)


def package_skills(out_dir: Path) -> list[Path]:
    """Write <out>/<name>/SKILL.md + <out>/<name>.zip per skill; returns zip paths."""
    scans = _scan_skills()
    if not scans:
        raise SystemExit("no skills found to package (is skills/ present?)")

    zips: list[Path] = []
    for scan in scans:
        # Re-read the frontmatter from disk rather than trusting scan fields
        # alone so a description edit between scan and write can't be missed;
        # scan already validated the file exists and parses.
        frontmatter = _parse_frontmatter(
            (scan.directory / "SKILL.md").read_text(encoding="utf-8")
        )
        stub = build_stub(
            scan.name, frontmatter.get("description", scan.description), scan.version
        )

        stub_dir = out_dir / scan.name
        stub_dir.mkdir(parents=True, exist_ok=True)
        (stub_dir / "SKILL.md").write_text(stub, encoding="utf-8")

        zip_path = out_dir / f"{scan.name}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(f"{scan.name}/SKILL.md", stub)
        zips.append(zip_path)
    return zips


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--out",
        type=Path,
        default=Path("dist/skill-stubs"),
        help="output directory (default: dist/skill-stubs)",
    )
    args = parser.parse_args()

    for zip_path in package_skills(args.out):
        print(f"wrote {zip_path} and {zip_path.with_suffix('')}/SKILL.md")


if __name__ == "__main__":
    main()
